# Generated by Django 4.2.7 on 2023-11-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100, verbose_name='Enter your title text')),
                ('description_text', models.TextField(verbose_name='Enter your description text')),
            ],
        ),
    ]
