# Generated by Django 4.2.7 on 2023-11-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='film/')),
                ('cost', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Horror', 'Horror'), ('Comedy', 'Comedy')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stringrun',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
