# Generated by Django 4.2.7 on 2023-11-16 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_filmmodel_alter_stringrun_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfishaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=100, verbose_name='enter your film name')),
                ('time_hall', models.TimeField(verbose_name='enter this time')),
                ('hall', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AlterModelOptions(
            name='filmmodel',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
    ]
