# Generated by Django 4.2.7 on 2023-11-29 05:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('text_review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='main_page.filmmodel')),
            ],
        ),
    ]
